# Generated by Django 3.2.4 on 2021-08-03 10:59

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('categories', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='task',
            managers=[
                ('EndedTasks', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='task',
            old_name='category_id',
            new_name='category',
        ),
    ]
