# Generated by Django 3.2.4 on 2021-08-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210803_1529'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='task',
            managers=[
            ],
        ),
    ]
